<HTML>
<center>
<p>SELAMAT DATANG DI APLIKASI CENAT-CENUT CINTA</p>
<p><blink><font color="red">PERINGATAN : </font></blink></p>
<p>HATI-HATI MENGGUNAKAN APLIKASI INI, KARENA DAPAT MENYEBABKAN PUTUS HUBUNGAN, GANGGUAN HATI, TAMBAH LENGKET DLL.</p>
</center>
</HTML>